### ISSUE TITLE
nav toggle

### ISSUE THREAD

**Issue by katz0018** [katz0018/saas-website#1]
@mpelletiervaillant

Hey so the toggle nav when pressed, the input doesn't disappear. Swell as the UL it self doesn't appear. I tried placing it on the top left corner of the website but its not moving over.

**Comment by mpelletiervaillant-zz** [comment]
I see that you have the .nav class written twice on different tags. This might be causing some confusion. Also, the nav tag itself should surround the entire thing like the picture I attached. Try fixing those.
<img width="438" alt="screen shot 2018-04-16 at 11 59 59 am" src="https://user-images.githubusercontent.com/22224981/38821540-c990787a-416e-11e8-99ae-f6f47dcf8765.png">

**Comment by mpelletiervaillant** [comment]
**the <nav> tag itself
